### ISSUE TITLE
Installation of the neuron has failed

### ISSUE THREAD

**Issue by Dimasua** [kalliope-project/kalliope_neuron_magic_mirror#3]
Hello guys, I'm installing this module but got the below error. Can you please elaborate on the settings part, where they are expected to be? Thanks in advance. 
![image](https://user-images.githubusercontent.com/956226/129685780-f2c3f67b-90bc-4280-bd4e-e672ecdb6eb6.png)

**Comment by Sispheor** [comment]
The output message is pretty clear. Invalid settings.
From what i can see here you are not placed in your brain folder.
Read the doc to learn how works Kalliope.

++
