### ISSUE TITLE
Is Kalliope Neuron Magic Mirror Kalliope 0.7 compliant?

### ISSUE THREAD

**Issue by Dimasua** [kalliope-project/kalliope_neuron_magic_mirror#4]
I have installed kalliope_neuron_magic_mirror but in the dna.yml I found that it is Kalliope 0.6 compliant.
As I'm using Kalliope 0.7, will it work with it?

![image](https://user-images.githubusercontent.com/956226/130270008-117e73c8-9ef9-42bc-94fd-3255acdbb50c.png)

**Comment by Sispheor** [comment]
yes
